/**:
  ros__parameters:
    base_frame: base_link
    use_imu: true
    use_3d_distortion_correction: false

# スキャンが始まってから終わるまでの間に車両が移動する
# この移動によって最初のデータポイントと最後のデータポイントの間の位置がずれて、歪みが発生する
# IMUや速度データを利用して、補正する


